# Generated by Django 4.0.2 on 2022-09-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nic', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('uc', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
